---
- name: Installing Tomcat9
  hosts: all
  tasks: 
  - name: Tomcat config
    apt:
     name: tomcat9
     state: present
     update_cache: yes
  - name: Tomcat admin
    apt:
      name: tomcat9-admin
      state: present
      update_cache: yes   
  - name: Copying  xml
    copy:
      src: /home/ubuntu/tomcat-users.xml
      dest: /etc/tomcat9

  - name: changing port
    replace:
     regexp: 8080
     replace: 9090
     path: /etc/tomcat9/server.xml
  - name: pause
    pause:
      minutes: 1
  - name: restart
    service:
      name: tomcat9
      state: restarted
  - name: checking with server1
    uri:
      url: http://172.31.25.126:9090
      status_code: 200
    
...       
           
